
# Generated by Django 3.1.2 on 2020-12-05 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.AddField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(related_name='group_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
