
# Generated by Django 3.1.2 on 2020-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_onboarduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_use',
            field=models.BooleanField(default=False),
        ),
    ]
