
# Generated by Django 3.1.2 on 2021-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201229_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
