
# Generated by Django 3.1.2 on 2021-01-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210130_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='group/cover_img/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group/image/'),
        ),
    ]
