
# Generated by Django 3.1.2 on 2021-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210130_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='direct_join',
        ),
        migrations.RemoveField(
            model_name='group',
            name='needs_moderation',
        ),
        migrations.RemoveField(
            model_name='group',
            name='private',
        ),
        migrations.AddField(
            model_name='group',
            name='members_request',
            field=models.CharField(choices=[('direct_join', 'Direct Join'), ('need_moderation', 'Needs Moderation')], default='direct_join', max_length=50, verbose_name='Member Request Type'),
        ),
    ]
