# FlowBack was created and project lead by Loke Hagberg. The design was
# made by Lina Forsberg. Emilio Müller helped constructing Flowback.
# Astroneatech created the code. It was primarily financed by David
# Madsen. It is a decision making platform.
# Copyright (C) 2021  Astroneatech AB
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

# Generated by Django 3.1.2 on 2021-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210130_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='direct_join',
        ),
        migrations.RemoveField(
            model_name='group',
            name='needs_moderation',
        ),
        migrations.RemoveField(
            model_name='group',
            name='private',
        ),
        migrations.AddField(
            model_name='group',
            name='members_request',
            field=models.CharField(choices=[('direct_join', 'Direct Join'), ('need_moderation', 'Needs Moderation')], default='direct_join', max_length=50, verbose_name='Member Request Type'),
        ),
    ]
