
# Generated by Django 3.1.2 on 2021-02-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_groupdocs_doc_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouprequest',
            unique_together={('group', 'participant')},
        ),
    ]
