
# Generated by Django 3.1.2 on 2021-02-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210216_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='poll_request',
            new_name='poll_approval',
        ),
    ]
