
# Generated by Django 3.1.2 on 2021-02-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210217_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members_request',
            field=models.CharField(choices=[('direct_approve', 'Direct Approve'), ('need_moderation', 'Needs Moderation')], default='direct_approve', max_length=50, verbose_name='Member Request Type'),
        ),
    ]
