
# Generated by Django 3.1.2 on 2021-02-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210219_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
