
# Generated by Django 3.1.2 on 2021-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210219_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members_request',
            field=models.CharField(choices=[('direct_join', 'Direct Join'), ('need_moderation', 'Needs Moderation')], default='direct_join', max_length=50, verbose_name='Member Request Type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='poll_approval',
            field=models.CharField(choices=[('direct_approve', 'Direct Approve'), ('need_moderation', 'Needs Moderation')], default='direct_approve', max_length=50, verbose_name='Poll Request Type'),
        ),
    ]
