
# Generated by Django 3.1.2 on 2021-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_friendchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendchatmessage',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
